### PR TITLE
feat: Allow inlining compile-time variables without curly braces

### PR DESCRIPTION
**Pull request by GearsDatapacks**
This Zoglin code:
```
namespace example

fn load() {
  &value = 10
  data modify storage example:load something set value &value
}
```
Now compiles to this MCFunction:
```mcfunction
data modify storage example:load something set value 10
```

### CODE REVIEW

**Comment by GearsDatapacks** [comment]
I wonder if this should apply to macro variable as well, so we can do `%var` instead of `&{%var}`

**Comment by moxvallix** [comment]
> I wonder if this should apply to macro variables as well, so we can do %var instead of &{%var}

I think that's a good idea.

Also, I think `&foo()` should be allowed too.

**Comment by GearsDatapacks** [comment]
> Also, I think `&foo()` should be allowed too.
With arguments as well? Because that could get tricky. I guess we can use the same method as we did for detecting the closing brace, so yeah that's probably fine

**Comment by moxvallix** [comment]
Well if we were removing arguments from
static expressions then its not really a problem right?

**Comment by GearsDatapacks** [comment]
Only from runtime calls, we still want to allow compile-time calls with arguments

**Comment by moxvallix** [comment]
Yeah true. I think we may need to re-think some of our parser / lexer setup, as some of our syntax doesn't really fit with it currently.

**Comment by GearsDatapacks** [comment]
Probably. But this approach seems to work pretty well for now

**Review by moxvallix — APPROVED** [review]
Looks good to me, I think this can be merged.

**Pull request merged**
